package com.cfox.droidmesh.installer

import org.junit.Assert.assertArrayEquals
import org.junit.Assert.assertEquals
import org.junit.Assert.assertFalse
import org.junit.Assert.assertNotEquals
import org.junit.Assert.assertSame
import org.junit.Assert.assertTrue
import org.junit.Test
import java.math.BigInteger
import java.nio.ByteBuffer
import java.nio.ByteOrder
import java.security.KeyPair
import java.security.KeyPairGenerator
import java.security.MessageDigest
import java.security.Signature
import java.security.interfaces.RSAPublicKey
import java.util.Base64

/**
 * [PROGRAMMATIC] INST-TEST-029/030/031: pins the two wire encodings adbd will accept and the
 * persistence of the keypair they are derived from. Every assertion here failed against the
 * shipped 0.1.0 (82) implementation, which sent an X.509 SubjectPublicKeyInfo blob that adbd
 * logged as "Invalid base64 key" and signed the auth token without its SHA-1 DigestInfo prefix.
 * See project/docs/SPEC/installer.md.
 */
class AdbAuthKeysTest {

    private val r32: BigInteger = BigInteger.ONE.shiftLeft(32)

    private fun referenceKeyBlob(): ByteArray {
        val line = javaClass.classLoader!!
            .getResourceAsStream("adb-reference-pubkey.txt")!!
            .use { String(it.readBytes(), Charsets.UTF_8) }
            .trim()
        return Base64.getDecoder().decode(line.substringBefore(' '))
    }

    private fun newKeyPair(): KeyPair {
        val kpg = KeyPairGenerator.getInstance("RSA")
        kpg.initialize(AdbAuthKeys.MODULUS_BITS)
        return kpg.generateKeyPair()
    }

    // INST-TEST-029: the reference blob is the public half of a keypair generated by adb's own
    // `adb keygen`, i.e. the exact encoding adbd accepts. Decoding it to (modulus, exponent) and
    // re-encoding with our encoder must reproduce all 524 bytes, including the two derived fields
    // (n0inv, rr) that a hand-rolled encoder gets wrong silently.
    @Test
    fun `INST-TEST-029 encodes an android_pubkey blob byte-identically to adb keygen`() {
        val reference = referenceKeyBlob()
        assertEquals(
            "reference fixture is not an android_pubkey blob",
            AdbAuthKeys.ENCODED_KEY_SIZE,
            reference.size
        )

        val (modulus, exponent) = AdbAuthKeys.decodePublicKey(reference)
        val reEncoded = AdbAuthKeys.encodePublicKey(modulus, exponent)

        assertArrayEquals(
            "re-encoding adb keygen's own public key must be byte-identical",
            reference,
            reEncoded
        )
    }

    // INST-TEST-029 (cont.): structural checks on a freshly generated key, plus the negative
    // control that the pre-fix X.509 encoding is specifically not what we emit. The base64 of an
    // RSA SubjectPublicKeyInfo always begins "MIIBIjAN" - that literal prefix is what the live
    // device logged back as "E adbd: Invalid base64 key MIIBIjAN..." on 2026-09-11.
    @Test
    fun `INST-TEST-029 encoded key is the android_pubkey struct and not an X509 SPKI`() {
        val keyPair = newKeyPair()
        val publicKey = keyPair.public as RSAPublicKey
        val encoded = AdbAuthKeys.encodePublicKey(publicKey)

        assertEquals(AdbAuthKeys.ENCODED_KEY_SIZE, encoded.size)

        val buf = ByteBuffer.wrap(encoded).order(ByteOrder.LITTLE_ENDIAN)
        assertEquals("modulus_size_words", 64, buf.int)

        val n0inv = BigInteger.valueOf(buf.int.toLong() and 0xFFFFFFFFL)
        val n0 = publicKey.modulus.mod(r32)
        assertEquals(
            "n0inv must satisfy n0inv * n[0] == -1 mod 2^32",
            r32.subtract(BigInteger.ONE),
            n0inv.multiply(n0).mod(r32)
        )

        val modulusLe = ByteArray(256)
        buf.get(modulusLe)
        assertArrayEquals(
            "modulus must be stored little-endian",
            littleEndian(publicKey.modulus),
            modulusLe
        )

        val rrLe = ByteArray(256)
        buf.get(rrLe)
        assertEquals(
            "rr must be (2^2048)^2 mod n",
            BigInteger.ONE.shiftLeft(4096).mod(publicKey.modulus),
            bigIntegerFromLittleEndian(rrLe)
        )

        assertEquals("exponent", 65537, buf.int)

        assertFalse(
            "must not emit the X.509 SubjectPublicKeyInfo encoding adbd rejects",
            encoded.contentEquals(publicKey.encoded)
        )
        assertFalse(
            "base64 payload must not be an X.509 SPKI (MIIBIjAN...)",
            Base64.getEncoder().encodeToString(encoded).startsWith("MIIBIjAN")
        )

        // The AUTH_RSAPUBLICKEY payload adbd parses is "<base64> <identity>\0".
        val payload = AdbAuthKeys.publicKeyAuthPayload(publicKey, "droidmesh@portal")
        assertEquals("payload must be NUL-terminated", 0.toByte(), payload.last())
        val text = String(payload, 0, payload.size - 1, Charsets.UTF_8)
        assertEquals("droidmesh@portal", text.substringAfter(' '))
        assertArrayEquals(
            "payload must carry the android_pubkey blob",
            encoded,
            Base64.getDecoder().decode(text.substringBefore(' '))
        )
    }

    // INST-TEST-030: adbd verifies with RSA_verify(NID_sha1, ...), so the signature must be
    // PKCS#1 v1.5 over the SHA-1 DigestInfo wrapping of the 20-byte token, not over the bare
    // token. Control: the JCE's own SHA1withRSA over a preimage whose digest is that token must
    // produce the identical signature.
    @Test
    fun `INST-TEST-030 signs the auth token as PKCS1 over its SHA-1 DigestInfo`() {
        val keyPair = newKeyPair()
        val preimage = "droidmesh adb auth token fixture".toByteArray(Charsets.UTF_8)
        val token = MessageDigest.getInstance("SHA-1").digest(preimage)
        assertEquals(20, token.size)

        val expected = Signature.getInstance("SHA1withRSA").run {
            initSign(keyPair.private)
            update(preimage)
            sign()
        }

        val actual = AdbAuthKeys.signToken(keyPair.private, token)

        assertEquals("RSA-2048 signature length", 256, actual.size)
        assertArrayEquals(
            "signature must match RSA_sign(NID_sha1, token) as adbd verifies it",
            expected,
            actual
        )

        val rawOverBareToken = javax.crypto.Cipher.getInstance("RSA/ECB/PKCS1Padding").run {
            init(javax.crypto.Cipher.ENCRYPT_MODE, keyPair.private)
            doFinal(token)
        }
        assertFalse(
            "must not sign the bare token (the pre-fix behavior adbd always rejected)",
            actual.contentEquals(rawOverBareToken)
        )
    }

    // INST-TEST-031: the keypair has to outlive the process, or every app restart presents adbd
    // a brand new key and re-prompts "Allow debugging from this computer?" on the TV screen -
    // which is unanswerable from a remote browser and is what made repair fail permanently.
    @Test
    fun `INST-TEST-031 reuses the stored keypair across processes and recovers from a corrupt file`() {
        val dir = kotlin.io.path.createTempDirectory(prefix = "adbkeys").toFile()
        dir.deleteOnExit()

        val first = AdbAuthKeys.loadOrCreate(dir)
        val second = AdbAuthKeys.loadOrCreate(dir)

        assertEquals(
            "a second process must load the same key, not mint a new one",
            (first.public as RSAPublicKey).modulus,
            (second.public as RSAPublicKey).modulus
        )
        assertArrayEquals(first.private.encoded, second.private.encoded)
        assertTrue(
            "the key must actually be on disk",
            dir.listFiles()?.any { it.isFile && it.length() > 0 } == true
        )

        val stored = dir.listFiles()!!.first { it.isFile }
        stored.writeBytes(byteArrayOf(0x2A, 0x2A, 0x2A))
        val third = AdbAuthKeys.loadOrCreate(dir)
        assertNotEquals(
            "an unreadable key file must be replaced, not reused",
            (second.public as RSAPublicKey).modulus,
            (third.public as RSAPublicKey).modulus
        )
        assertEquals(
            "and the replacement must persist",
            (third.public as RSAPublicKey).modulus,
            (AdbAuthKeys.loadOrCreate(dir).public as RSAPublicKey).modulus
        )

        // The production callers reach the key through keyPair(), not loadOrCreate: pin that the
        // accessor serves what is on disk and caches it, so the per-process-key regression cannot
        // come back through the accessor while loadOrCreate stays correct.
        AdbAuthKeys.init(dir)
        val viaAccessor = AdbAuthKeys.keyPair()
        assertEquals(
            "keyPair() must serve the persisted key, not mint a per-process one",
            (third.public as RSAPublicKey).modulus,
            (viaAccessor.public as RSAPublicKey).modulus
        )
        assertSame("keyPair() must cache within a process", viaAccessor, AdbAuthKeys.keyPair())
    }

    private fun littleEndian(value: BigInteger): ByteArray {
        val be = value.toByteArray()
        val out = ByteArray(256)
        var written = 0
        var i = be.size - 1
        while (i >= 0 && written < 256) {
            out[written++] = be[i]
            i--
        }
        return out
    }

    private fun bigIntegerFromLittleEndian(le: ByteArray): BigInteger {
        val be = ByteArray(le.size + 1)
        for (i in le.indices) {
            be[be.size - 1 - i] = le[i]
        }
        return BigInteger(be)
    }
}
